[lint]
select = ["E4", "E7", "E9", "F", "B", "C4", "I"]

[lint.per-file-ignores]
"autoddg/generate_description.py" = ["E501"]
"autoddg/generate_topic.py" = ["E501"]
"autoddg/data_process.py" = ["E501"]
"autoddg/search.py" = ["E501"]
"autoddg/utils.py" = ["E501"]
